### ISSUE TITLE
(load "compile") results in an error to do with let-fluid

### ISSUE THREAD

**Issue by jkabrg** [hnarayanan/sicm#1]
I installed mit-scheme using homebrew on OSX. I git-pulled, navigated to scmutils/src and ran mit-scheme; then I inputted (load "compile") and got the following error:

```
;Loading "compile.scm"...
;  Loading "general/comutils.so"... done
;  Loading "general/let-macro.so"... done
;Unbound variable: let-fluid
;To continue, call RESTART with an option number:
; (RESTART 2) => Define let-fluid to a given value.
; (RESTART 1) => Return to read-eval-print level 1.
```

**Comment by hnarayanan** [comment]
I have seen this too. This is because the code as it is in the repo needs a development version of scheme to compile. Go back in the history of this project (git checkout an older commit before I updated to the latest version of the sicm code) and you'll see that it works.

**Comment by jkabrg** [comment]
Which older commit?

**Comment by hnarayanan** [comment]
Anything before https://github.com/hnarayanan/sicm/commit/a04bf659d818506c6bc099411ad18ed8618fb9fb 😊
